Repository afaneca/myfin, pull requests merged in 2025-02, with the labels that each got.

#419 7.4.1
  .dockerignore
  .github/FUNDING.yml
  .github/workflows/build-container-frontend.yml
  Dockerfile
  docker-compose.yml
  nginx.conf
  package.json
Labels: enhancement, maintenance

#423 422-replace-mariadb-with-mysql-in-docker-compose
  docker-compose.yml
Labels: bug

#424 7.4.2
  Dockerfile
  docker-compose.yml
  package.json
Labels: bug

#426 425-soft-rebrand-to-myfin-budget
  Dockerfile
  assets/logo_blue_transparentbg.png
  assets/logo_blue_transparentbg.psd
  assets/logo_dark_transparentbg.png
  assets/logo_dark_transparentbg.psd
  assets/logo_light_plain_transparentbg.png
  assets/logo_light_plain_transparentbg.psd
  assets/logo_light_transparentbg.png
  assets/logo_light_transparentbg.psd
  docker-compose.yml
  index.html
  public/res/logo_blue_transparentbg.png
  public/res/logo_dark_transparentbg.png
  public/res/logo_light_plain_transparentbg.png
  public/res/logo_light_transparentbg.png
  src/components/MyFinSidebar.tsx
  src/features/auth/Login.tsx
  src/features/dashboard/Dashboard.tsx
  src/features/dashboard/MonthlyOverviewChart.tsx
Labels: enhancement

#429 428-fix-hide-last-updated-timestamp-from-dashboard-when-there-are-no-transactions
  src/features/dashboard/Dashboard.tsx
  src/services/account/accountHooks.ts
Labels: bug

#431 430-fix-translation-for-account-status
  src/features/accounts/Accounts.tsx
Labels: bug

#432 7.5.0
  Dockerfile
  assets/logo_blue_transparentbg.png
  assets/logo_blue_transparentbg.psd
  assets/logo_dark_transparentbg.png
  assets/logo_dark_transparentbg.psd
  assets/logo_light_plain_transparentbg.png
  assets/logo_light_plain_transparentbg.psd
  assets/logo_light_transparentbg.png
  assets/logo_light_transparentbg.psd
  docker-compose.yml
  index.html
  package.json
  public/res/logo_blue_transparentbg.png
  public/res/logo_dark_transparentbg.png
  public/res/logo_light_plain_transparentbg.png
  public/res/logo_light_transparentbg.png
  src/components/MyFinSidebar.tsx
  src/features/accounts/Accounts.tsx
  src/features/auth/Login.tsx
  src/features/dashboard/Dashboard.tsx
  src/features/dashboard/MonthlyOverviewChart.tsx
  src/services/account/accountHooks.ts
Labels: bug, enhancement

#437 Fix: status translation for categories #436
  src/components/TopSummary.tsx
  src/features/categories/Categories.tsx
  src/i18n.ts
Labels: bug

#441 Fix source typo
  src/providers/SnackbarProvider.tsx
Labels: bug

#443 Fix: Top summary values corrupted after navigating to accounts #442
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  src/services/user/userHooks.ts
Labels: bug

#445 Fix image urls on docker compose file
  docker-compose.yml
Labels: bug

#455 Docker: Support multi-arch builds #453
  .github/workflows/build-container-frontend.yml
Labels: maintenance

#458 Tweak: improve light theme contrast #457
  src/features/auth/RecoverPassword.tsx
  src/features/budgets/list/BudgetList.tsx
  src/features/invest/InvestDashboard.tsx
  src/features/profile/Profile.tsx
  src/features/setup/Setup.tsx
Labels: enhancement
